### ISSUE TITLE
Can UnreachableMaster handle this mechanism automatically?

### ISSUE THREAD

**Issue by jackiesre721** [openark/orchestrator#1041]
`Often encounter power failures and cannot handle,Is there a parameter that can control this trigger recovery`

**Comment by shlomi-noach** [comment]
Hi, sorry, seems like I missed this issue while on vacation. You want to trigger a recovery based on `UnreachableMaster`? This is not supported and will not be supported -- because that's not a good indicator for a failover. The question I have for you is: why do you see `UnreachableMaster` and not `DeadMaster`? How come the replicas don't see the master as dead? Please consider this [replication configuration](https://github.com/github/orchestrator/blob/master/docs/configuration-failure-detection.md#mysql-configuration).
