### ISSUE TITLE
How many times orchestrator takes to decree a Master node failure

### ISSUE THREAD

**Issue by jsecchiero** [openark/orchestrator#1084]
Is possible to clarify this with some example and all parameters involved?

https://github.com/openark/orchestrator/blob/master/docs/failure-detection.md

```
The naive approach further mitigates false positives by running n tests spaced by t-long intervals. 
```

**Comment by pparshin** [comment]
There is an option `InstancePollSeconds` which determines how often to probe each instance in a cluster.

Every `RecoveryPollSeconds` (basically a hardcoded constant equals 1 second) orchestrator analyses the topology. If it find a problem, it immediately starts a new analyze in order to get the latest state of the cluster. When slaves confirms that master is not available, orchestrator executes a failover.

Note that you should tune your MySQL setup according to the [documentation](https://github.com/openark/orchestrator/blob/master/docs/configuration-failure-detection.md).

**Comment by jsecchiero** [comment]
Thanks for info @ParshinPavel
