### ISSUE TITLE
CoMasterRecoveryMustPromoteOtherCoMaster is false but still it is using true.

### ISSUE THREAD

**Issue by adepollusaikumar** [openark/orchestrator#1109]
Hi ,

Here is my topology :
I have 2 masters and 3 slaves attached to one of the masters.
When M1 and M2 are down , Slaves are not getting promoted . Below is the error. Am I missing anything here? And my config is like I have disabled `CoMasterRecoveryMustPromoteOtherCoMaster=false ` don't know why it is still using the as true.

> 2020-04-01 21:32:59 ERROR RecoverDeadCoMaster: could not manage to promote other-co-master E01:3306; was only able to promote EQ03:3306; CoMasterRecoveryMustPromoteOtherCoMaster is true, therefore failing

M1 
|
M2 ->|S1
       ->|S2
       ->|S3

**Comment by shlomi-noach** [comment]
Right. The debug message is misleading and should be changed. I see this in the code:

https://github.com/openark/orchestrator/blob/0366aafd2a6bbe353fc6f554b2caef245a7ebcd4/go/logic/topology_recovery.go#L1269-L1273

So, `mustPromoteOtherCoMaster` turned to `true` because the co-master was writeable. The debug message should have pointed that out, but wrongly claimed "oMasterRecoveryMustPromoteOtherCoMaster is true"

To explain again, if the co-master is writeable, then we _have to_ failover to that co-master -- if it's writeable, we can assume it's receiving writes already...

**Comment by shlomi-noach** [comment]
https://github.com/openark/orchestrator/pull/1162 fixes the debug message
