### ISSUE TITLE
Question: Master to replica

### ISSUE THREAD

**Issue by mike-code** [openark/orchestrator#1235]
This question might only be somewhat related to the orchestrator itself and it's most likely due to my lack of understanding on building a MySQL cluster. Also it's quite difficult to find straight answer for my question so it must be that my assumptions are fundamentally wrong yet I just want to make sure they really are.

So for test purposes I wanted to create a `M -> S -> S` topology. I started up 4 "plain" mysql docker containers on the same machine (ports 3307, 3308 and 3309 as well as the "control" (backend) server for orchestrator (3306).

Now I said to the orchestrator, hey there are three servers there available, all are on 127.0.0.1, ports 330(7|8|9), they are docker images so ignore their hostnames, just map the 127.0.0.1 to alias `foobar` and put them in a single cluster.

Orchestrator says, no way, these are 3 masters and I'm going to put them into three separate clusters where the first two are going to be named `ip:port`and the last one is going to be aliased `foobar` (which is OK, I saw an issue on GH but can't find it now, where it was explained why only 1 out of 3 servers here are going to be aliased and it'll always be the latest one discovered that matches the key condition)

Now I'd like to say, yes I know they are all masters and I want you to take 3308 and 3309 and make them 3307's slaves and again, put them into single cluster.
But.. it doesn't look like this kind of flow is supported as I can't find a command/API endpoint for this purpose? It only allows me to work on **existing** replicas in **the same** cluster. Orchestrator wants 3308 and 3309 to already be slaves or am I misreading something? 

To shed some more light on my case — I have very little (nearly no) experience with DBA and I wanted to avoid (for starters) any "control" queries that I  have to issue directly to the servers such as setting master, checking gtids, mapping binlogs and whatnot. I just wanted to spin up a server (which by default will always be a master on it's first run) and tell it: forget about your tables, your history and your legacy — you are now becoming a replica of 3307, and I wanted orchestrator to take care of this.

Is there any reference in the docs that I recklessly missed or it wasn't there because that's totally not how replications in mysql works and I'm missing plain basics here?

Thanks

**Comment by shlomi-noach** [comment]
>  forget about your tables, your history and your legacy — you are now becoming a replica of 3307

@mike-code , yeah, this is exactly the kind of thing `orchestrator` _does not do_, unfortunately for you. "stock" `orchestrator` observers topologies, and can fix failures, but it infers relationships from the state of the topologies.

To elaborate a bit, MySQL doesn't have a concept of a "replication cluster". Servers in a replication topology are just servers that happen to replicate from each other. There's no cluster "entity" in MySQL. And so orchestrator doesn't, either. `orchestrator` understands what a cluster is when it sees one. If there's a replicaiton chain, `orchestrator` analyzes it, can refactor it; it can tell that "ok, these servers belong together until I'm told otherwise". 

But it will not:

- Decide that two servers belong together if they were never in touch in the first place
- Touch your data **in any way** (`orchestrator` shouldn't have access to your data). It will not drop tables.


Your question comes at interesting timing because just last week @sougou demonstrated an integration of `orchestrator` and `Vitess`. Now, `Vitess` does exactly those things you wanted: it _knows_ that some servers belong together. It knows_ it should aggregate them together. It _knows_ how they should interact. The `orchestrator` integration is on a neverending task of making the topology look like what `Vitess` wants it to look like. If there's "stranded" servers, it will connect them to what it thinks should be the master. It will make replication work. It will ensure all but the master are read-only. etc. etc. etc. See the webinar here: https://youtu.be/JVHi2oN3lxM

Now, I'm not sure if you plan to install Vitess on top of your servers. And for disclosure I now work for PlanetScale, the maintainers of Vitess. The idea, though, is that Vitess will take care of your database infrastructure for you. Right now admittedly setting up vitess has its own toil -- but potentially check it out. https://vitess.io/docs/

**Comment by mike-code** [comment]
Wow that's an exhaustive reply

It looks very promising although the entry curve seems to be quite steep for my use case, or maybe that's just first impression. I don't (yet) need scalability, just a failover system with possibility to easily create **new** replicas, assign them to an existing "cluster" and/or detach replica from a cluster to become a master of a new "cluster" on it's own -- things like that. I'll study the Vitess docs and try to find something there. Thanks! :)
