### ISSUE TITLE
Master to become slave when recovering from outage?

### ISSUE THREAD

**Issue by dynek** [openark/orchestrator#190]
Hello,

Hoped to find some IRC channel to ask few questions but did not find any, too  bad :-)
When master election occurs because current one goes down, is the previous master supposed to become slave when coming back alive? Otherwise how will it catch-up with modifications?

**Setup:**
```
srvmysql1.domain.com:3306   [0s,ok,5.7.18-log,rw,ROW,>>]
+ srvmysql2.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
+ srvmysql3.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
+ srvmysql4.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
```

This with GTID, as mentioned and log_slave_updates.

I shut down mysql service on srvmysql1 and then I trigger a manual (cli) election of a new master:

```
srvmysql1.domain.com:3306     [unknown,invalid,5.7.18-log,rw,ROW,>>,downtimed]
- srvmysql2.domain.com:3306   [null,nonreplicating,5.7.18-log,ro,ROW,>>,GTID]
  + srvmysql3.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
  + srvmysql4.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
```

srvmysql2 takes the role of "master" for 3 and 4.

**1. Why don't srvmysql2 become a master (instead of a mix of master and slave)?**

Now let me turn on srvmysql1:

```
srvmysql1.domain.com:3306     [0s,ok,5.7.18-log,rw,ROW,>>]
- srvmysql2.domain.com:3306   [null,nonreplicating,5.7.18-log,ro,ROW,>>,GTID]
  + srvmysql3.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
  + srvmysql4.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
```

**2. Why don't srvmysql1 become a slave of srvmysql2 when it's coming back alive?**

Otherwise, how do I transfer delta from srvmysql2 to srvmysql1?

Thank you

**Comment by shlomi-noach** [comment]
> Hoped to find some IRC channel to ask few questions but did not find any, too bad :-)

There's this desolate group: https://groups.google.com/forum/#!forum/orchestrator-mysql

#### Pro tip:

use three backticks for multiline snippets, such as:
```
srvmysql1.domain.com:3306   [0s,ok,5.7.18-log,rw,ROW,>>]
+ srvmysql2.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
+ srvmysql3.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
+ srvmysql4.domain.com:3306 [0s,ok,5.7.18-log,ro,ROW,>>,GTID]
```

See how I edited your original comment.

> When master election occurs because current one goes down, is the previous master supposed to become slave when coming back alive? Otherwise how will it catch-up with modifications?

You can't expect it to be come a replica because it potentially (likely, in many environments) have applied more transactions that its replicas. That is, it is _more up to date_ than the promoted replica. As such, it will likely break on replication.

> Why don't srvmysql2 become a master (instead of a mix of master and slave)?

Please set:

```
"ApplyMySQLPromotionAfterMasterFailover": true,
```
in your config. This will issue a `RESET SLAVE ALL; set read_only=0;` on the promoted server.

This is an endless debate: should `orchestrator` do that by default or not? Reason for _not_ doing that is that `RESET SLAVE ALL` loses data if relay logs are not all applied. And otherwise some environments like to have this operation done from external scripts.

> Why don't srvmysql1 become a slave of srvmysql2 when it's coming back alive?

Because it will have conflicting data (See above)

> Otherwise, how do I transfer delta from srvmysql2 to srvmysql1?

backup + restore would be the safest, especially with GTID.

**Comment by dynek** [comment]
Hello,

Sorry for coming back to you so late on the question. Thanks for the pro tip. I'm not very familiar with (Github) markup but this one I knew :-) I just thought it looked OK as copy/pasted.

All of what you say obviously makes sense and I was able to get the behavior I was expecting from ApplyMySQLPromotionAfterMasterFailover - thanks for that!

Now how would I go about having the previous master join the dance again? Backup + restore and modify its configuration on disk to become a slave instead of a master, right?

Thank you!

**Comment by shlomi-noach** [comment]
> I'm not very familiar with (Github) markup

It's called _markdown_ 😛  https://guides.github.com/features/mastering-markdown/

> Now how would I go about having the previous master join the dance again? Backup + restore and modify its configuration on disk to become a slave instead of a master, right?

Yes indeed.

**Comment by dynek** [comment]
Ah ah ! Early in the morning :-)

Thank you for your time and answers.

**Comment by shlomi-noach** [comment]
Hey Ristreto and Arpeggio are my favorites!

**Comment by dynek** [comment]
I prefer Dharkan et Kazaar :-)
