### ISSUE TITLE
a question about Failover step

### ISSUE THREAD

**Issue by guoguobo** [openark/orchestrator#293]
I have a cluster like:
```
+A:9999
  -B:9999
  -C:9999
  -D:9999
```
A,B,C and D is in the same dc.The promotion rule of B is prefer and others are neutral.
When DeadMaster failover occured,the cluster  like:
```
+B:9999
   -C:9999
       -D:9999
```
I check the log and find orchestrator first promote replica:C:9999 as master,B:9999 and D:9999 are picked  as candidate replacement.Then orchestrator find the promotion rule of B is prefer,so it try and take its master.And things seems ok.
But i have a question about the cluster‘s final form.Why the cluster not like:
```
+B:9999
  -C:9999
  -D:9999
```

**Comment by shlomi-noach** [comment]
Seems like a perfect behavior with current logic. Your question is good. The short answer: mostly technical debt.

The long answer:
When failing over a master we are under some time pressure. Promoting a new replica (C) takes time. We then realize it's not the one we want and invest more time (a few seconds) promoting B on top of C.
Spending further time to make D replicate from B is quite possible, and yet also slightly risky. Risky, not in the sense that it could go wrong, but in the sense of postponing the finalization of the promotion.
Now, that is not strictly correct, because we could move D to replicate from B asynchronously (postponed operation). This is a relatively recent feature that can be utilized.
And yet, we ended up with a stable, functional setup.
