### ISSUE TITLE
Crash when using sqlite + raft

### ISSUE THREAD

**Issue by hmcgonig** [openark/orchestrator#321]
Hey, we currently run orchestrator 3.0.2 and occasionally a node in our cluster will crash, then fail to start back up with the following raft error:
```
2017-10-19 19:49:44 INFO new raft created
2017/10/19 19:49:44 [INFO] raft: Node at 172.18.191.200:10008 [Follower] entering Follower state (Leader: "")
2017-10-19 19:49:44 INFO Starting HTTP listener on :3000
2017/10/19 19:49:45 [DEBUG] raft-net: 172.18.191.200:10008 accepted connection from: 172.18.187.132:58894
2017/10/19 19:49:45 [WARN] raft: Failed to get previous log: 31294 log not found (last: 0)
2017/10/19 19:49:45 [ERR] raft: Failed to create snapshot to install: RelSnapshotStore does not support remote snapshot stores
2017-10-19 19:49:45 FATAL RelSnapshotStore does not support remote snapshot stores
```

If I had to take a blind guess at why it can't restart, in our current environment we were trying to just use ephemeral storage for orchestrator. I was under the impression that the node would just reinitialize by communicating with the rest of the cluster, is that not the case? I can see how that may cause issues if raft configuration/ state was stored on disk somewhere.

**Comment by shlomi-noach** [comment]
@hmcgonig you are correct -- but hold tight! https://github.com/github/orchestrator/pull/300 is coming to solve that.

If you're using `sqlite`, this should pretty much solve everything.

In the case of `MySQL`, not entirely: since if a node completely crashes and MySQL loses all data, it also loses the privileges table. So if your databases restart clean, `orchestraor` is likely to not have the privileges to write to it. It will at least take a `puppet` run (or similar) to re-apply privileges to your DB before `orchestrator` could touch it.

**Comment by hmcgonig** [comment]
Excellent, I'm using sqlite, so this should be fantastic. Thanks for the quick response!

**Comment by hmcgonig** [comment]
Closing this as #300 did the trick.

**Comment by shlomi-noach** [comment]
Heh, wait till you see #332 and use `:memory:` for your SQLite backend!

**Comment by hmcgonig** [comment]
😮 definitely excited for that.

**Comment by shlomi-noach** [comment]
fixed and released in https://github.com/github/orchestrator/releases/tag/v3.0.3
