### ISSUE TITLE
Raft single-mode does not work well

### ISSUE THREAD

**Issue by davygeek** [openark/orchestrator#439]
> I test raft with single-mode, config like 
`"RaftEnabled": true,
  "RaftDataDir": "/export/Data/orchestrator",
  "RaftBind": "127.0.0.1",
  "RaftAdvertise": "127.0.0.1",
  "DefaultRaftPort": 10008,
  "RaftNodes": [
    "127.0.0.1"
  ]`

it doesn't work well

After change code from 
`if len(peerNodes) == 0 && len(peers) <= 1 {
		log.Infof("enabling single-node mode")
		config.EnableSingleNode = true
		config.DisableBootstrapAfterElect = false
}`

to 
`if len(peerNodes) <= 1 && len(peers) <= 1 {
		log.Infof("enabling single-node mode")
		config.EnableSingleNode = true
		config.DisableBootstrapAfterElect = false
}`

it's work well。 

Can you accept a new PR change 
`len(peerNodes) == 0`
to 
`len(peerNodes) <= 1`

Or there are other design ideas I do not understand？

thank you.

**Comment by shlomi-noach** [comment]
@davygeek Thank you. Before answering, I'm happy if you can please describe what "doesn't work well" means. What do you get? What do you expect?

I do believe I see the issue, though. To quickly make single-raft-node work for you, please specify `"RaftNodes": [],`.

I agree your setup is expected to work. However, I'm unsure whether `if len(peerNodes) <= 1` is the correct solution since we must test the value specified in your `RaftNodes` matches the value in `RaftBind`.

**Comment by shlomi-noach** [comment]
Please see https://github.com/github/orchestrator/pull/440

**Comment by davygeek** [comment]
@shlomi-noach thanks for you answering.
