### ISSUE TITLE
Reverse proxy and CLI

### ISSUE THREAD

**Issue by samiahlroos** [openark/orchestrator#452]
We were quite happy to remove HAProxy from our orchestrator/raft setup and use the built in reverse proxy functionality, thanks for that! We do have a small issue though.

In our setup orchestrator-client is installed on each MySQL server. The problem is, those servers can only talk to orchestrator instances in the same datacenter. So if Raft leader happens to be in DC-A, orchestrator-client doesn't work in DC-B. 
Orchestrator instances themselves can communicate with each other, that is why it works using HAProxy in front of Orchestrator.

Basically all this would work with the reverse proxy as well, but orchestrator-client insists on finding Raft leader and talking directly to it. To work around this I changed `detect_leader_api()` to call `/api/raft-health` instead of `/api/leader-check`, so the client is happy to talk to any healthy Raft member.

Same applies to the `raft_leader()` function -- the client first verifies that it is talking to the leader, and then asks the leader who the leader is. Leaving out that verification makes the client work for us.

What I wonder is, would there be any drawbacks to this? What is going to break if the client requests get proxied? I imagine it should "just work".

**Comment by shlomi-noach** [comment]
> Basically all this would work with the reverse proxy as well, but orchestrator-client insists on finding Raft leader and talking directly to it. To work around this I changed detect_leader_api() to call /api/raft-health instead of /api/leader-check, so the client is happy to talk to any healthy Raft member.

If you only give `orchestrator-client` a single `orchestrator` address, it will use it whether it's a leader or not.

I assume your problem is that you have multiple `orchestrator` services in each DC, and you want `orchestrator-client` to connect to any of them, but never to any other. Is that the case? Do you provide each `orchestrator-client` the list of its local DC services? I'm missing context.

Generally speaking it is valid to call `/api/raft-health` instead of `/api/leader-check`, but then again for _other_ people, this would mean `orchestrator-client` could pick a server which is in another DC, leading to possible two cross-DC hops per request (`orchestrator-client` to other DC `orchestrator`, then reverse-proxy to other-other-DC `orchestrator` leader).

**Comment by samiahlroos** [comment]
> but then again for other people, this would mean orchestrator-client could pick a server which is in another DC

That is exactly the kind of drawback I was wondering about. 😃 

> If you only give orchestrator-client a single orchestrator address, it will use it whether it's a leader or not.

Looking at the code again looks like I missed that fact. I should be able to work with that. Thank you!
