### ISSUE TITLE
If one data center crash, can we promote multiple cluster parallel?

### ISSUE THREAD

**Issue by benmaoer** [openark/orchestrator#519]
Hi, @shlomi-noach, if a data center crash, how could we parallel promote multiple clusters？I‘ve found the limit in  go/logic/orchestrator.go , I guess it's serially to recover different clusters, is it just to protect intermediate-master cluster?
```
        case <-recoveryTick:
            go func() {
                if IsLeaderOrActive() {
                    go ClearActiveFailureDetections()
                    go ClearActiveRecoveries()
                    go ExpireBlockedRecoveries()
                    go AcknowledgeCrashedRecoveries()
                    go inst.ExpireInstanceAnalysisChangelog()

                    go func() {
                        // This function is non re-entrant (it can only be running once at any point in time)
                        if atomic.CompareAndSwapInt64(&recoveryEntrance, 0, 1) {
                            defer atomic.StoreInt64(&recoveryEntrance, 0)
                        } else {
                            return
                        }
                        if time.Since(continuousDiscoveryStartTime) >= checkAndRecoverWaitPeriod {
                            CheckAndRecover(nil, nil, false)
                        } else {
                            log.Debugf("Waiting for %+v seconds to pass before running failure detection/recovery", checkAndRecoverWaitPeriod.Seconds())
                        }
                    }()
                }
            }()
```

**Comment by shlomi-noach** [comment]
Hi @benmaoer, this is supported and should work for you. The code you've quoted doesn't have anything to do with parallelization of recoveries.

This is more relevant: https://github.com/github/orchestrator/blob/351af88a4b6a449307fda2f669cbe7d8323b6dfd/go/logic/topology_recovery.go#L1519-L1522

**Comment by benmaoer** [comment]
Does the code I've quoted  mean at the same time, only one goroutine do check and recover, before the goroutine  finished work or timeout, there is no goroutine could do the same thing. Inside CheckAndRecover function, it's still parallel recoveries

**Comment by shlomi-noach** [comment]
The code you've quoted runs every 1 second, and asynchronously invokes the `CheckAndRecover()` function, which reads analysis and then asynchronously runs all required recoveries.

1 second later, the code you've quoted will run again, and asynchronously run `CheckAndRecover()`  which will asynchronously invoke all required recoveries _that have not been invoked  yet and that are not blocking newcoming recoveries_.

etc.

The `CheckAndRecover` function spends almost no time executing. Typically it's below `100ms` as I recall, and for VeryLargeSetups™ it may run almost 1 second or even slightly above.

There should not be an issue with running multiple failovers at the same time due to a data center going down.
