### ISSUE TITLE
Store full topology in key-value store (feature request)

### ISSUE THREAD

**Issue by ThijsFeryn** [openark/orchestrator#537]
Hi,

I've been experimenting with Orchestrator and I really like the fact that the details for the current master can be stored in a key-value store.

I'd find it very useful if the other nodes of the cluster would also have their host/port/ip stored in a key-value store.

This would make the discovery process of the entire topology quite easy. I could use Consul Template to retrieve master and connected slaves in order to provision HAProxy or ProxySQL.

I know you have this information. Does this seem like a useful addition to discovery in conjunction with key-value stores?

Thanks for considering.

**Comment by shlomi-noach** [comment]
Hi,
`orchestrator` exposes all that information through its API, consider running `orchestrator-client -c all-instances` or `orchestrator-client -c api -path all-instances | jq .[].Key.Hostname`.

I would like to avoid storing all instances in KV. Instances continuously change (added, removed) which means more frequent updates to KV. Which also means more traffic between `orchestrator/raft` nodes, assuming `orchestrator/raft` is used, which goes against the desire to keep the `raft` communication minimal.
Also it means maintaining adding/updates/removal/expiration of entries in KV, which is basically what happens in the backend `database_instance` table, so there's duplication of work to it.
And then what if cluster name/alias changes, and managing information in KV format as opposed to relational.

I appreciate that consul-template is useful (using it myself) and that it can help populate ProxySQL, and that it works with Consul. If that's the path you want, I'd advise running your own scheduled script that would read from `orchestrator`'s API and update Consul accordingly. I think that while writing this script you will meet with many considerations (retention/removal/etc).

FWIW in our setup `orchestrator` is not the source of truth for proxy rosters. And I think such dependency is not the best. Our internal inventory manager is the source of truth (this could be Consul for you). `orchestrator` reflects the reality, but I'm not sure the reality should dictate the roster; it's an interesting discussion though.

**Comment by ThijsFeryn** [comment]
Thanks, Shlomi.

This was a very useful conversation with a bunch of takeaways.

We can close the ticket now, because I now have the info to proceed.

Thanks again!

Thijs

**Comment by utdrmac** [comment]
@shlomi-noach I am attempting to use consul-template to reconstruct/update proxysql config in my training but finding it difficult to do so since orc does not maintain list of slaves in KV. Could you share how you are using consul-template in this manner? I understand that you have an external 'source of truth' for all your mysql servers, and maybe that is the key to getting c-t working correctly.

I'd say that having yet-another-service as 'inventory/truth' is overkill for smaller shops that just have simple topology. In many cases, Orc "is" the source of truth.

I noticed that the failover hook scripts all receive the slaves as ENV or { } template variables. Why do these get the slaves list but KV does not?

**Comment by shlomi-noach** [comment]
@utdrmac we take a different approach.

First, we do have a different source of truth; we have a server inventory service that can tell us "which hosts are running mysql in cluster X". However, that is of lesser importance.

The roster doesn't change. When we failover we don't need to update the list of replicas. This is because we put everything in the roster: master, replicas, even potentially irrelevant servers (though this is going away).

The trick is that we run http-checks on the backend servers, and those http-checks report back saying "yes, I want to be part of the pool", or "no, please don't send traffic my way".

This is illustrated in https://githubengineering.com/context-aware-mysql-pools-via-haproxy/

**Comment by shlomi-noach** [comment]
@utdrmac I suggest the following approach, in your case:

- use post failover hooks to find who the master is
- run `orchestrator-client -c which-replica` to get list of immediate replicas of promoted master (or use `-c which-cluster-instances` for all)
- possibly filter that list according to your own logic
- update consul with that list

This isn't something I'd build into `orchestrator` as it open the door to so many variations; each user would want it differently.

Oh, and possibly utilize tags: https://github.com/github/orchestrator/blob/master/docs/tags.md
