### ISSUE TITLE
master-master replication is lost after promotion

### ISSUE THREAD

**Issue by ghost** [openark/orchestrator#724]
We have the following replication topology (master-master with slave on each, GTID,  "CoMasterRecoveryMustPromoteOtherCoMaster": false):
```
M1 -> S1
↕
M2 -> S2 
```
If M1 crashes, the recovered topology is the following:
`S1 -> M2 -> S2`
If there any way to keep master-master like this:
`S1 <-> M2 -> S2`
 or I need to use hooks for this?
Thank you.

**Comment by shlomi-noach** [comment]
https://github.com/github/orchestrator/blob/0d99be49d0997792a8b5a85049505acc77e2257e/go/logic/topology_recovery.go#L1179-L1183

Hope this answers 😆 

Please use hooks.

**Comment by ghost** [comment]
Thank you for quick response, @shlomi-noach .
What I noticed also in this config. 
If after crash of M1, M2 is the most up-to date replica, then I can not promote S1 even, if I set "prefer" to it. It always promote M2:

> 2018-11-20 11:12:29 INFO topology_recovery: promoted instance M2 is not the suggested candidate S1. Will see what can be done
> 2018-11-20 11:12:29 INFO topology_recovery: suggested candidate S1 is replica of promoted instance M2. Will try and take its master
> 2018-11-20 11:12:29 ERROR M2 is co-master. Cannot take it.
> 

Looks like it fails on TakeMaster func
 https://github.com/github/orchestrator/blob/b4cc5895929fa8fb3f104af80aa5b6129245295b/go/inst/instance_topology.go#L1660

**Comment by shlomi-noach** [comment]
To better understand:

- you have M1, M2 co-masters, and S1 replica
- M1 fails
- You prefer to promote S1 instead of M2 which is already co-master?

Asking our of interest.

Generally speaking this is (should be) supported, depending on `CoMasterRecoveryMustPromoteOtherCoMaster`. 
- Seems like you're reporting this to be broken (in which case I'd _really_ appreciate a new Issue)
- What is the value in your config?

**Comment by ghost** [comment]
Right. I will open new issue and describe the case there.
Thank you.
