### ISSUE TITLE
NETWORK IS not ok

### ISSUE THREAD

**Issue by dbaspace** [openark/orchestrator#737]
WHEN the NETWORK IS NOT OK ,master is alive
egg:
server monitor(172.16.0.75) IS MANAGER 
![image](https://user-images.githubusercontent.com/23513271/48937368-d11fb500-ef48-11e8-93c5-0e6518437fe7.png)
WHEN I at master exe 
  iptables -t filter -I INPUT   -s 172.16.0.75/32 -p tcp  --dport 3318 -j DROP
master is not drift ,not offline
log:
![image](https://user-images.githubusercontent.com/23513271/48937196-5060b900-ef48-11e8-9ccc-e6a994bc4d69.png)
why  not drift？
![image](https://user-images.githubusercontent.com/23513271/48938012-e5fd4800-ef4a-11e8-92d3-7e1f397a0e7e.png)

**Comment by shlomi-noach** [comment]
Hi,
We have a language barrier here and I'll do my best to answer, though I'm not sure I understand the question.
What is "drift"? I'm trying to understand what word would Google translate into "drift".

Failover?

So, I think you're asking: why didn't `orchestrator` run a failover?
The answer is that the replica sees the master just fine. See https://github.com/github/orchestrator/blob/master/docs/failure-detection.md#deadmaster
Because the replica says "I can see he master and replicate from it", `orchestrator` assumes it's it own problem for not seeing the master.

**Comment by dbaspace** [comment]
my English is poor,thank you sir,you are right,
