### ISSUE TITLE
Why are all nodes detecting at the same time?

### ISSUE THREAD

**Issue by yangzhongj** [openark/orchestrator#897]
Hello, I have a question. In orchestrator/raft, why are all nodes detecting at the same time, will they summarize the results of their detection to comprehensively judge MySQL? I think that only the leader can detect it himself.

**Comment by shlomi-noach** [comment]
This is so that if the leader node dies or gets network isolated, the other nodes (and in particular the new leader) will have an independent view of the problem. This is especially oriented towards multi-datacenter setups, where an entire DC can get network isolated. Such scenario will be auto-analyzed by the orchestrator nodes outside the isolated datacenter.

Please consider watching https://www.youtube.com/watch?v=YzhkTu0lSvk

**Comment by yangzhongj** [comment]
I think there is a possibility of a single node detection error judgment. Assuming that only the orchestrator and the mysql instance network of the local room are jittery, the orchestrator-leader thinks this needs to be failover. It is more reasonable to use the majority to participate in the judgment.

**Comment by shlomi-noach** [comment]
> I think there is a possibility of a single node detection error judgment. 

Did you happen to read how detection works? https://github.com/github/orchestrator/blob/master/docs/failure-detection.md

There is no "single node detection error judgment" because failovers are not based on single node monitoring.

This logic has *very* low noise and *very* high accuracy. I use the works "low" and "high" without providing numbers, I know. Generally speaking I haven't seen neither a false positive nor a false negative in a long time. 

Please consider watching https://www.youtube.com/watch?time_continue=11&v=E96ItlGSxN0 or reviewing https://speakerdeck.com/shlominoach/reliable-crash-detection-and-failover-with-orchestrator.

There was also thinking to further add majority analysis, but at this time I don't see that it is needed.

But please do make sure to read the docs first, https://github.com/github/orchestrator/blob/master/docs/failure-detection.md

**Comment by yangzhongj** [comment]
yes, i kown

**Comment by shlomi-noach** [comment]
The current approach negates single-host errors.

**Comment by yangzhongj** [comment]
I love orchestrator very much ，very good.

**Comment by shlomi-noach** [comment]
oh, thank you for saying so!

**Comment by shlomi-noach** [comment]
Closed as no further action is needed.
