### ISSUE TITLE
Unsupported configuration, no error?

### ISSUE THREAD

**Issue by feiazifeiazi** [openark/orchestrator#910]
using orchestrator  v3.0.14.
Someone told me that a tool was orchestrator.
told me a config name is DelayMasterPromotionIfSQLThreadNotUpToDate.
I've been testing for a long time. a long time. But it didn't work, very disappointed.
I downloaded the source code of 3.0.14, There is no code in it.
Why didn't you make a error?
Write a configuration at random， still not error..
I......
me......
u......
he......
she......
-------------
Make a suggestion:
1. Unsupported configuration, make a error.
2. Which API outputs all configuration values? If not, can you add it?

**Comment by feiazifeiazi** [comment]
why?

**Comment by shlomi-noach** [comment]
Hi, I wasn't sure if this was a real post or not.

I do understand the essence of the request: you wish to get an error when a variable is invalid. That's a perfectly legitimate request. There's actually a (quite old) PR to fix that: https://github.com/github/orchestrator/pull/95, which I haven't gotten round to merge as I had a few reservations.

In this world of open source and community, many users are submitting bug reports, questions and requests for enhancements, and a few people (or a single person) to handle them all. To that effect, maintainers really need the issue to be explained well. The format you chose to describe the issue is not helpful to the maintainer (myself in this case). All bold large letters, emotional expressions, text that just doesn't belong in a coherent sentence, other text that may have been translated by Google Translate, irrelevant messages. I don't mean to dissect your initial comment to the ground but it isn't something that helps the maintainer do their work.

I made explicit guidance for how to submit an issue, and it is in https://github.com/github/orchestrator/issues/new, which you could have read and followed. It's actually very open ended.

It is difficult to assume your comment is serious in first glance. For example, here is the source code of 3.0.14:https://github.com/github/orchestrator/archive/v3.0.14.tar.gz . There is source in it. I took it from here: https://github.com/github/orchestrator/releases/tag/v3.0.14

And so there is some expectation that the user will make a small investment in trying their best to explain their problem in a reasonably understandable English description (English isn't my native language, either), and provide some evidence that they did their testing and experiments before claiming there's an error.

I hope this clarifies why I decided to not dwell on this issue, which I find almost non-actionable (even though I am eventually able to understand the essence of your request, once I'm impressed that it was serious).

Kind regards

**Comment by feiazifeiazi** [comment]
@shlomi-noach 

Thank you for your reply.

Thank you for understanding my problem.

I am from China. My English is not very good. I'm sorry.

I use the translation software.
